"use client";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { BrowserRouter, Link, Outlet, Route, Routes } from "react-router-dom";
import Staff from "./pages/staff";
import Home from "./page";
import { Col, Nav, Navbar, NavbarBrand, NavItem, Row } from "reactstrap";
import Positions from "./pages/positions";
import TicketTypes from "./pages/ticketTypes";
import EventTypes from "./pages/eventType";
import AdvertisingAgencies from "./pages/advertisingAgencies";
import Events from "./pages/event";
import GiftTicket from "./pages/giftTicket";
import Invitations from "./pages/invitations";
import Refund from "./pages/refund";
import RegularCustomers from "./pages/regularCustomers";
import Rescheduled from "./pages/rescheduled";
import Sponsors from "./pages/sponsors";
import Ticket from "./pages/ticket";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route index element={<Home />} />
            <Route path="staff" element={<Staff />} />
            <Route path="positions" element={<Positions />} />
            <Route path="tickettypes" element={<TicketTypes />} />
            <Route path="advertagency" element={<AdvertisingAgencies />} />
            <Route path="events" element={<Events />} />
            <Route path="giftTickets" element={<GiftTicket />} />
            <Route path="invitations" element={<Invitations />} />
            <Route path="refund" element={<Refund />} />
            <Route path="regularCustomer" element={<RegularCustomers />} />
            <Route path="rescheduled" element={<Rescheduled />} />
            <Route path="sposnors" element={<Sponsors />} />
            <Route path="ticket" element={<Ticket />} />
            <Route path="eventtypes" element={<EventTypes />} />
          </Route>
        </Routes>
      </BrowserRouter>
    </html>
  );
}
function Layout() {
  return (
    <div>
      <Navbar color="light">
        <NavbarBrand href="/">Cursova by Anastasiya Prohorchuck</NavbarBrand>
        <Nav className="me-auto" navbar>
          <Row>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/staff">Staff</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/positions">Positions</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/tickettypes">Ticket Types</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/eventtypes">Event Types</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/advertagency">Advertisement agencies</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/events">Events</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/giftTickets">Gift Tickets</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/invitations">Invitations</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/refund">Refunds</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/regularCustomer">Regular Customers</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/rescheduled">Rescheduled events</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/sposnors">Sponsors</Link>
              </NavItem>
            </Col>
            <Col>
              <NavItem className="navbar-brand">
                <Link to="/ticket">Tickets</Link>
              </NavItem>
            </Col>
          </Row>
        </Nav>
      </Navbar>
      <Outlet />
    </div>
  );
}
